### ISSUE TITLE
Reading the result once

### ISSUE THREAD

**Issue by nightmareside15** [sercona/Owon-Multimeters#2]
Hello. Thanks for the wonderful project!

I want to ask if is there any way to make the script work for like, one result instead of continuous reading?
I tried using
`timeout 5 ./owon_multi_cli -a F4:B8:98:0A:18:E3 -t b35t -j /home/ltimonsyst1/ltiProgram/test.csv`
but then it didn't save any data to csv files.
 
 While using
 `./owon_multi_cli -a F4:B8:98:0A:18:E3 -t b35t -j /home/ltimonsyst1/ltiProgram/test.csv | head -n 1`
 doesn't make the script working in the end.
 
 
 Thank you very much!

**Comment by sercona** [comment]
great idea.  I'll add that feature.  a 'run once' kind of thing.  thanks!

**Comment by sercona** [comment]
update pushed to origin.  give it a try now.  use the -1 switch.

**Comment by nightmareside15** [comment]
> update pushed to origin. give it a try now. use the -1 switch.

Honestly I didn't expect such a fast response. Not to mention the updated script in that matter!
Tried it. It is working as I need it to! Now I can make it run in node-red while having the data saved in the db without needed to wait the long process! Now I can even compare the measurement data with the set point to determine OK or NG material.
Once more, thank you very much for this project!

**Comment by sercona** [comment]
update: there is now a test version for ESP32.  It outputs to serial console as a stream.  Maybe that could be useful for your application.  No need for linux ble services, all you need is to be able to read serial at 115k and parse some simple fields out.
